version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: avito-postgres
    environment:
      POSTGRES_DB: avito_task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

      - ./migrations/000001_avito-task.up.sql:/docker-entrypoint-initdb.d/000001_avito-task.sql

  app:
    build: .
    container_name: avito-app
    depends_on:
      - db
    environment:

      HTTP_PORT: "8080"


      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1111"
      POSTGRES_DB: avito_task
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data:
